### ISSUE TITLE
Unable to find certain words

### ISSUE THREAD

**Issue by ghost** [louisrli/anki-reverso-cloze#2]
Hey! Me again :)
So I downloaded a frequency list and it can't find some of the most common words.
Wondering if it has anything to do with the fact that they're not in upper case and these are mainly used as such?
Processing |                                | 1/500 Nothing found on Reverso: **я**
Processing |                                | 4/500 Nothing found on Reverso: **в**
Processing |                                | 5/500 Nothing found on Reverso: **и**

Thanks for your help

**Comment by louisrli** [comment]
Hello! Those don't show up when you search them on Reverso either, upper or lowercase (in Russian the words you listed are not necessarily used in upper, as they are, in English, "I" the pronoun, "in" the preposition, "and" the conjunction, respectively). In general Reverso seems to ignore one letter words.

No results:
https://context.reverso.net/translation/russian-english/%D1%8F

For example if I try another language, also nothing shows up for "i":
https://context.reverso.net/translation/italian-english/i

I'll consider adding an explicit warning + skipping one letter words

**Comment by ghost** [comment]
Is there any way to retrieve definitions or context/examples for these one letter words?

**Comment by louisrli** [comment]
No, but honestly, I wouldn't recommend using this tool for this use case -- figuring out the first N words in a language without some basic foundation (which usually includes the one letter words). For the very, very beginning, one of the premade decks would probably be more useful (I personally wouldn't use this for the first N words either).

Usually these cards would be most effective when you can use the cloze sentences effectively. That is, you can recognize some of the words around it etc. For example, it's unlikely that any of the Reverso example sentences will be useful to you if you don't know the pronoun "I" yet in a language.

**Comment by ghost** [comment]
Thanks for the suggestion!
